name: Build On Push Master, Build On Pull Request

env:
  ARTIFACT_APK: artifact_apk
  ARTIFACT_APK_PATH: artifact_apk_path
on:
  pull_request:
    branches:    
      - 'mas**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: AssembleDebug Check
      run: ./gradlew clean assembleDebug

    - name: Upload APK artifact path
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_APK_PATH }}
        path: app/build/**/*.apk
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        retention-days: 60      
      
    - name: Download APK artifact path
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_APK_PATH }}
