name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
  if: ${{ github.event.comment.body == 'jrb'||github.event.comment.body == ''||github.event.comment.body == null}}
  uses: ./.github/workflows/BuildOnPullRequest
