name: Pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: ./diplom/workflows/BuildOnPullRequest
